package ca.hccis.bookstore.bo;

import ca.hccis.bookstore.entity.Book;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for the cost calculation in BookBO.
 *
 * The first three tests were written by hand using a test driven development
 * approach, one at a time, each failing before the logic to satisfy it was
 * written.  The remainder were generated by supplying the project README and
 * the Book entity class to an AI tool, as required by part two of the
 * assignment, and then reviewed and run.
 *
 * @author Kay Pitre
 * @since 20260928
 */
public class BookBOTest {

    /**
     * Tolerance for comparing currency held in a double.
     */
    private static final double TOLERANCE = 0.001;

    // ------------------------------------------------------------------
    // Part 1 - written by hand, test driven development approach
    // ------------------------------------------------------------------

    /**
     * A book released before 1950 carries a 50% premium.
     *
     * Written using a test driven development approach.  This test was written
     * before any logic existed in calculateCost, run to confirm it failed
     * against the NO_COST sentinel, and only then was the premium logic added.
     *
     * 2 copies at $10.00 released in 1949 = 20.00 * 1.50 = 30.00
     */
    @Test
    @DisplayName("Pre-1950 book carries a 50% premium")
    public void testPre1950Premium() {
        Book book = new Book("The Old One", 10.00, "1949", 2);

        double actual = BookBO.calculateCost(book);

        assertEquals(30.00, actual, TOLERANCE);
    }

    /**
     * A book released between 1970 and 1989 carries a 20% premium.
     *
     * Written using a test driven development approach.  Written and run
     * before calculateCost handled this band at all, confirmed failing against
     * the NO_COST sentinel, and only then was the 20% band added.
     *
     * 3 copies at $12.99 released in 1977 = 38.97 * 1.20 = 46.764
     */
    @Test
    @DisplayName("1970s book carries a 20% premium")
    public void testSeventiesPremium() {
        Book book = new Book("The Shining", 12.99, "1977", 3);

        double actual = BookBO.calculateCost(book);

        assertEquals(46.764, actual, TOLERANCE);
    }

    /**
     * A book released after the premium bands carries no premium at all.
     *
     * Written using a test driven development approach.  Written and run
     * before calculateCost returned anything but the NO_COST sentinel for a
     * modern title, and only then was the no-premium case added.
     *
     * The second assertion is the point of this test.  It is not enough that
     * the cost is right; the premium must demonstrably not have been applied,
     * so the test also asserts the result is not the 50% figure.
     *
     * 4 copies at $18.50 released in 2001 = 74.00, unchanged
     */
    @Test
    @DisplayName("Modern book carries no premium")
    public void testModernNoPremium() {
        Book book = new Book("Life of Pi", 18.50, "2001", 4);

        double actual = BookBO.calculateCost(book);

        assertEquals(74.00, actual, TOLERANCE);
        assertNotEquals(74.00 * BookBO.PREMIUM_HIGH_MULTIPLIER, actual, TOLERANCE);
    }

    // ------------------------------------------------------------------
    // Part 2 - AI generated from the README and the Book entity, reviewed
    // ------------------------------------------------------------------

    /**
     * AI generated.  1949 is inside the high premium band, 1950 is not.
     */
    @Test
    @DisplayName("Boundary: 1949 premium, 1950 none")
    public void testBoundary1950() {
        assertEquals(BookBO.PREMIUM_HIGH_MULTIPLIER,
                BookBO.getVintageMultiplier("1949"), TOLERANCE);
        assertEquals(BookBO.NO_PREMIUM_MULTIPLIER,
                BookBO.getVintageMultiplier("1950"), TOLERANCE);
    }

    /**
     * AI generated.  1969 gets no premium, 1970 opens the 20% band.
     */
    @Test
    @DisplayName("Boundary: 1969 none, 1970 premium")
    public void testBoundary1970() {
        assertEquals(BookBO.NO_PREMIUM_MULTIPLIER,
                BookBO.getVintageMultiplier("1969"), TOLERANCE);
        assertEquals(BookBO.PREMIUM_LOW_MULTIPLIER,
                BookBO.getVintageMultiplier("1970"), TOLERANCE);
    }

    /**
     * AI generated.  1989 closes the 20% band, 1990 is outside it.
     */
    @Test
    @DisplayName("Boundary: 1989 premium, 1990 none")
    public void testBoundary1990() {
        assertEquals(BookBO.PREMIUM_LOW_MULTIPLIER,
                BookBO.getVintageMultiplier("1989"), TOLERANCE);
        assertEquals(BookBO.NO_PREMIUM_MULTIPLIER,
                BookBO.getVintageMultiplier("1990"), TOLERANCE);
    }

    /**
     * AI generated.  The quote overload prices the quantity asked for rather
     * than the quantity the record says sold.
     *
     * 5 copies at $20.00 released in 1985 = 100.00 * 1.20 = 120.00, even
     * though the record says only 1 copy sold.
     */
    @Test
    @DisplayName("Quote overload prices the requested quantity")
    public void testQuoteQuantity() {
        Book book = new Book("Neuromancer", 20.00, "1985", 1);

        double actual = BookBO.calculateCost(book, 5);

        assertEquals(120.00, actual, TOLERANCE);
        assertNotEquals(BookBO.calculateCost(book), actual, TOLERANCE);
    }

    /**
     * AI generated.  A vintage title costs more than a modern one at the same
     * price and quantity.
     */
    @Test
    @DisplayName("Vintage costs more than modern at equal price")
    public void testVintageCostsMore() {
        Book vintage = new Book("Vintage Title", 15.00, "1930", 2);
        Book modern = new Book("Modern Title", 15.00, "2020", 2);

        assertTrue(BookBO.calculateCost(vintage) > BookBO.calculateCost(modern),
                "A pre-1950 title should cost more than a modern one at the same price");
    }

    /**
     * AI generated.  Nothing sold costs nothing.
     */
    @Test
    @DisplayName("Zero copies sold costs nothing")
    public void testZeroSold() {
        Book book = new Book("Unsold Title", 45.00, "1935", 0);

        assertEquals(0.00, BookBO.calculateCost(book), TOLERANCE);
    }

    /**
     * AI generated.  An unreadable release year returns the sentinel rather
     * than throwing, so a bad row cannot bring the report down.
     */
    @Test
    @DisplayName("Unreadable release year returns NO_COST")
    public void testBadYear() {
        Book book = new Book("Bad Data", 10.00, "not a year", 3);

        assertDoesNotThrow(() -> BookBO.calculateCost(book));
        assertEquals(BookBO.NO_COST, BookBO.calculateCost(book), TOLERANCE);
    }

    /**
     * AI generated.  A null record returns the sentinel rather than throwing.
     */
    @Test
    @DisplayName("Null record returns NO_COST")
    public void testNullBook() {
        assertDoesNotThrow(() -> BookBO.calculateCost(null));
        assertEquals(BookBO.NO_COST, BookBO.calculateCost(null), TOLERANCE);
    }
}
